### ISSUE TITLE
Recenze

### ISSUE THREAD

**Issue by micreas** [danielconka1993/reas-projekt#1]
Ahoj, Dan nás pověřil, abychom se ti na to mrkli a sepsali ti k tomu nějakou konstruktivní kritiku, takže jsem se toho ujal.

Začal bych tím pozitivním, tím co jsi dodržel a co jsi udělal navíc.

Nechybí tu React, použil jsi git, nasadil jsi to na Netlify a jako bonus jsi přidal i výpis nabídek, což podle mě v zadání ani nebylo. To se cení.

Akorát je škoda, že jsi ten čas, který jsi věnoval výpisu, nevěnoval tomu backendu, jelikož tady je jako backend použitý Firebase. Na Firebase není nic špatného. Jen v našem zadání bylo explicitně Mongo, protože nás zajímalo, jak si poradíš se setupem jednoduchého serveru, API a databáze. To je za mě zásadní mínus.

Co se týče funkčnosti. Formulář projít jde, je to dostatečně responzivní. Jen teda nesmíš mít ve jménu "áíé" a možná ještě nějaká další písmena.

Zároveň z nějakého důvodu používáš jednu sadu regexů při zadávání a další při odeslání. To podle mě taky nedává smysl. Celkově je v těch regexech docela chaos. Co se týče jmen nemá podle mě smysl být moc striktní. U telefonu a emailů tam už jo, to už je nějak standardizované. Jen takový point pro zlepšení. Na validaci existují knihovny jako např. Yup, nebo Joi. Můžeš si v nich sestavit validační schémata a lokalizovat error message.

Osobně bych to asi ještě víc rozsekal do komponent. Např. jeden komponent na jeden krok formuláře. Máš tam vysekané jen ty inputy.

To jsou ty zásadnější problémy.

Mezi ty méně důležité bych zařadil asi tohle:
- kód není očividně ničím naformátovaný (např. pomocí prettier)
- CSS v češtině s diakritikou, názvy komponent v češtině mimo pages directory. Standardem je dnes angličtina.
- našel jsem i nějaký zakomentovaný kód, to by také v gitu být nemělo pokud nejde třeba o nějaký example použití funkce nebo tak
- nepoužil jsi typescript

To je tak nějak všechno co mě trklo.

**Comment by danielconka1993** [comment]
Díky Micreasi za rozsáhlý feedback. Učím se kde se dá a každá informace navíc se mi hodí. Rozhodně zapracuju na MongoDB, se kterou jsem doteď neměl žádnou zkušenost a proto jsem vybral DB, se kterou jsem již v souladu. 

Ten 2 regex jsem tam dal proto, aby při zadávání emailu nezadal něco ve styl "@hooohe.com" nebo pokud zadá automatické vyplnění.

Ještě jednou moc děkuju, rozhodně na tom udělám ještě změny.

**Comment by danielconka1993** [comment]
Ten 2 regex jsem tam dal proto, aby při zadávání emailu nezadal neco ve styl "@hooohe.com"

**Comment by danielconka1993** [comment]
Zdravím tě Micreasi,
rád udělal jsem skeleton zadání (jen se 6 inputy type=text), ale ve funkčním mongoDB + express. A rád bych to nasadil na Vercel, ale ať jsem do vercel.json zadal cokoliv dle návodů, nic mi nefungovalo a stránku mi to vyhazovalo jako 404 stále. A byl bych velice rád pokud by jsi mi s tím pomohl, jelikož bez nasazení na web a jeho používání mohu express + mongoDB používat čistě jen jako studijní materiál.

odkaz na projekt: #https://github.com/danielconka1993/skeleton-express-mongoDB

Při importovaní na Vercel projektu z GitHubu jsem  zadal do:
1. Build and Output Settings - Output Directory - client/build
                                              - Install Command - npm install && cd client && npm install
                                              
2. Environment Variables - Key - DB_CONNECT
                                        - Value (Will Be Encrypted) - mongodb+srv://pykejavzlykej:surikata@nabidkadb.ynpj1xc.mongodb.net/?retryWrites=true&w=majority&appName=AtlasApp
                                        - !!!! má to být bez mezer !!!!!


- Environment Variables jsem přidal a deploydnul.

- přilohou zasílám env v txt formátu
- .env má byt ve složce server
[env.txt](https://github.com/danielconka1993/reas-projekt/files/13328843/env.txt)

Pokud by jsi mi poradil, měl by jsi mé nehynoucí sympatie protože už s tím bojuju pořádnou dobu a nemohu a nikam se neposouvám. 

Čonkys

**Comment by micreas** [comment]
Ahoj, klidně mi říkej Michale.

On je podle mě problém v tom, že Vercel není úplně stavěný na standalone backendy. Jsou docela striktní v tom, jak musíš mít to API napsané, aby to tam šlo nasadit. Docela simple guide mají tady. Zkus to:

https://vercel.com/guides/using-express-with-vercel#standalone-express

Btw. být tebou to trochu přestrukturuju ten server. (myslím složkově) Zkoušel jsem si to jen v rychlosti rozběhat a předělal jsem to nějak takhle. všechny ty soubory pro server jsou ve složce server, veškerý javascript je ve složce src. 

<img width="242" alt="image" src="https://github.com/danielconka1993/reas-projekt/assets/61692860/4a610f6d-608f-4c72-b3e9-3442be4af2e6">

Taky se hodí přidat tam start script do package.json. Cloudy se toho většinou chytají.
```JSON
{
  "name": "new",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node src/server.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.3.1",
    "express": "^4.18.2",
    "mongodb": "4.1",
    "mongoose": "^8.0.0"
  },
  "devDependencies": {
    "nodemon": "^3.0.1"
  }
}
```

Taky si myslím, že by se ti s tím lépe pracovalo, kdyby jsi to měl ve dvou oddělených repozitářích. Jeden pro frontend, druhý pro backend a měj package jsony atd. v root složce. Vercel se pak taky lépe chytá.

**Comment by danielconka1993** [comment]
Ahoj, díky Michale, 
udělal jsem jak jsi psal, ale bohužel mám výsledek stejný a nezdařilý. Vytvořil jsem nový repozitor na GitHub [https://github.com/danielconka1993/test/](url), zde je odkaz na nahraný web - [https://vercel.com/arevyhs-projects/test](url).

Tentokrát jsem použil při deploy do: 
Output Directory - client/build
Install Command - cd server && cd root && npm install && cd client && cd root && npm install

**Comment by micreas** [comment]
Ahoj,
nezlob se, ale nemám čas to procházet moc do detailů. Řekl jsem si, že tohle by ti mohlo pomoct asi nejvíc.

Udělal jsem pro tebe example repozitáře jak pro ten frontend, tak pro ten backend.

Express backend nasazený na Vercelu:
Repo: https://github.com/micreas/express-api-for-vercel-example
Ukázka responsu backendu: https://express-api-for-vercel-example.vercel.app/api

React (Next.js) frontend nasazený na Vercelu:
Repo: https://github.com/micreas/next-js-for-vercel-example
Nasazený web: https://next-js-for-vercel-example.vercel.app/

Dvě separátní repa, základní konfigurace. (jen jsem klikal na potvrdit na Vercelu)

Můžeš si to projít a klidně si to forkni.
